csrf_token: ImNlZTg5NGMxNTgwY2VhZTdjM2M2ZWNhYWFkNDhhNTAwZWNiYmQ2YTYi.ZCnNTw.-xpjnprHYX7mY7bQbxDwnio02zM
hardware_acceleration: true
mode: production
next: false
report_background_image: null
tests:
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
- csrf_token: null
  name: null
  value: false
users:
- csrf_token: null
  email: null
  password: null
  user_type: null
