csrf_token: ImNlZTg5NGMxNTgwY2VhZTdjM2M2ZWNhYWFkNDhhNTAwZWNiYmQ2YTYi.ZCm6YA.pNXFKbaf_OSE5kO-62wZKFQJnxg
hardware_acceleration: false
mode: null
next: false
report_background_image:
  filename: maxresdefault.jpg
  path: C:\Users\user\PycharmProjects\pythonInterviewProject\static\report_background_image\maxresdefault.jpg
tests:
- name: Test 1
  value: false
- name: Test 2
  value: false
- name: Test 3
  value: false
- name: Test 4
  value: false
- name: Test 5
  value: false
- name: Test 6
  value: true
- name: Test 7
  value: false
- name: Test 8
  value: false
- name: Test 9
  value: false
- name: Test 10
  value: false
users:
- csrf_token: null
  email: s
  password: s
  user_type: admin
